-- No-auth persistence policies.
-- FinOS v1 intentionally does not use Supabase Auth. The anon client needs read/write access.
-- profile_id is an application filter only, not a database security boundary.
alter table profiles enable row level security;
alter table accounts enable row level security;
alter table categories enable row level security;
alter table transactions enable row level security;
alter table recurring_transactions enable row level security;
alter table debts enable row level security;
alter table debt_payments enable row level security;
alter table budgets enable row level security;
alter table goals enable row level security;
alter table goal_contributions enable row level security;
alter table monthly_snapshots enable row level security;
alter table alerts enable row level security;
alter table settings enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert, update on profiles, accounts, categories, transactions, recurring_transactions, debts, debt_payments, budgets, goals, goal_contributions, alerts, settings to anon, authenticated;
grant select, insert on monthly_snapshots to anon, authenticated;
grant select on monthly_summary, account_balances, budget_progress, debt_progress, goal_progress, financial_health, dashboard_overview to anon, authenticated;
grant execute on function calculate_cashflow(uuid, integer, integer) to anon, authenticated;
grant execute on function calculate_liquidity(uuid) to anon, authenticated;
grant execute on function calculate_budget_usage(uuid) to anon, authenticated;
grant execute on function calculate_debt_ratio(uuid, integer, integer) to anon, authenticated;
grant execute on function calculate_goal_eta(uuid) to anon, authenticated;
grant execute on function calculate_financial_score(uuid, integer, integer) to anon, authenticated;
grant execute on function create_month_snapshot(uuid, integer, integer) to anon, authenticated;
grant execute on function generate_dashboard(uuid, integer, integer) to anon, authenticated;
grant execute on function generate_monthly_report(uuid, integer, integer) to anon, authenticated;
grant execute on function reset_database() to anon, authenticated;

create policy profiles_no_auth_select on profiles for select using (true);
create policy profiles_no_auth_insert on profiles for insert with check (true);
create policy profiles_no_auth_update on profiles for update using (true) with check (true);
create policy accounts_no_auth_select on accounts for select using (true);
create policy accounts_no_auth_insert on accounts for insert with check (true);
create policy accounts_no_auth_update on accounts for update using (true) with check (true);
create policy categories_no_auth_select on categories for select using (true);
create policy categories_no_auth_insert on categories for insert with check (true);
create policy categories_no_auth_update on categories for update using (true) with check (true);
create policy transactions_no_auth_select on transactions for select using (true);
create policy transactions_no_auth_insert on transactions for insert with check (true);
create policy transactions_no_auth_update on transactions for update using (true) with check (true);
create policy recurring_transactions_no_auth_select on recurring_transactions for select using (true);
create policy recurring_transactions_no_auth_insert on recurring_transactions for insert with check (true);
create policy recurring_transactions_no_auth_update on recurring_transactions for update using (true) with check (true);
create policy debts_no_auth_select on debts for select using (true);
create policy debts_no_auth_insert on debts for insert with check (true);
create policy debts_no_auth_update on debts for update using (true) with check (true);
create policy debt_payments_no_auth_select on debt_payments for select using (true);
create policy debt_payments_no_auth_insert on debt_payments for insert with check (true);
create policy debt_payments_no_auth_update on debt_payments for update using (true) with check (true);
create policy budgets_no_auth_select on budgets for select using (true);
create policy budgets_no_auth_insert on budgets for insert with check (true);
create policy budgets_no_auth_update on budgets for update using (true) with check (true);
create policy goals_no_auth_select on goals for select using (true);
create policy goals_no_auth_insert on goals for insert with check (true);
create policy goals_no_auth_update on goals for update using (true) with check (true);
create policy goal_contributions_no_auth_select on goal_contributions for select using (true);
create policy goal_contributions_no_auth_insert on goal_contributions for insert with check (true);
create policy goal_contributions_no_auth_update on goal_contributions for update using (true) with check (true);
create policy monthly_snapshots_no_auth_select on monthly_snapshots for select using (true);
create policy monthly_snapshots_no_auth_insert on monthly_snapshots for insert with check (true);
create policy alerts_no_auth_select on alerts for select using (true);
create policy alerts_no_auth_insert on alerts for insert with check (true);
create policy alerts_no_auth_update on alerts for update using (true) with check (true);
create policy settings_no_auth_select on settings for select using (true);
create policy settings_no_auth_insert on settings for insert with check (true);
create policy settings_no_auth_update on settings for update using (true) with check (true);
